data:
  DB            : postgresql://postgres:pcl@A5A@192.168.135.15:5432/road_network
  log_dir       : /home/pcl/traffic/RoadNetworkCreator_by_View/log
  area          : /home/pcl/Data/minio_server/input/Shenzhen_boundary_district_level_wgs.geojson
  df_matching   : /home/pcl/Data/minio_server/input/panos_matching.csv
  df_pred_memo  : /home/pcl/Data/minio_server/input/lane_shape_predict_memo.csv
  pano_dir      : /home/pcl/Data/minio_server/panos
  pano_group_dir: /home/pcl/Data/minio_server/tmp
  tmp           : /home/pcl/Data/minio_server/tmp
  input_dir     : /home/pcl/Data/minio_server/input
  lstr_api      : http://192.168.135.15:5000/lstr
  proxy_pool    : http://192.168.135.15:5555/random
  
osm:
  osm_highway_type_dict:
    motorway: motorway
    motorway_link: motorway
    trunk: trunk
    trunk_link: trunk
    primary: primary
    primary_link: primary
    secondary: secondary
    secondary_link: secondary
    tertiary: tertiary
    tertiary_link: tertiary
    residential: residential
    residential_link: residential
    service: service
    services: service
    cycleway: cycleway
    footway: footway
    pedestrian: footway
    steps: footway
    track: track
    unclassified: unclassified
model:
  model_dir: data/model/HetETA_toy
  method: HetETA
  max_diffusion_step: 2
  num_nodes: 300
  num_rnn_layers: 1
  rnn_units: 11
  seq_len: 4
  days: 4
  weeks: 4
  road_net_num: 7
  car_net_num: 1
  heads_num: 1
train:
  base_lr: 0.01
  lr_decay_ratio: 0.15
  lr_decay_epoch: 35
  dropout: 0.0
  epochs: 100
  epsilon: 0.005
  max_grad_norm: 5
  optimizer: amsgrad
  patience: 12
  threshold: 3
  regular_rate: 0.0001
  gpu_num: 1

# BBOX = [113.92348,22.57034, 113.94372,22.5855] # 留仙洞区域
# BBOX = [113.92389,22.54080, 113.95558,22.55791] # 科技园中片区
# BBOX = [114.04133,22.52903, 114.0645,22.55213] # 福田核心城区
